### PR TITLE
Run cargo fix

### PR DESCRIPTION
**Pull request by AngelOnFira**
Part of RVT-3553 and RVT-3466

### CODE REVIEW

**Comment by AngelOnFira** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/365?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #360** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/360?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #357** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/357?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #358** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/358?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #359** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/359?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
          * **PR #365** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/365?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈
            * **PR #366** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/366?utm_source=stack-comment-icon" target="_blank">Graphite</a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/rivet-gg/rivet/365?utm_source=stack-comment).

**Review by NathanFlurry — CHANGES_REQUESTED** [review]
All uses of `let _crdb = .*` can be removed completely. There's some other dead code but nbd.

**Review by NathanFlurry — APPROVED** [review]
Re last comment: probably should be in another commit, so I'll approve

**Comment by NathanFlurry** [comment]
https://linear.app/rivet-gg/issue/RVT-3607/remove-uses-of-let-crdb-=

**Review by NathanFlurry — APPROVED** [review]

**Pull request merged**
