### PR TITLE
chore: publish user-create-complete

### PR DESCRIPTION
**Pull request by MasterPtato**
feat(Infra): Loops welcome email

### CODE REVIEW

**Comment by MasterPtato** [comment]
Current dependencies on/for this PR:
* **#539** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/539?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/rivet-gg/rivet/539?utm_source=stack-comment).

**Review by AngelOnFira — APPROVED** [review]
LGTM, added a conventional commit message to the body (feel free to rewrite if needed)

**Review by NathanFlurry — CHANGES_REQUESTED** [review]
needs to be in ee, please close this pr

**Comment by MasterPtato** [comment]
@NathanFlurry this can't need to be closed, it has changes required for the ee portion to work

**Review by NathanFlurry — APPROVED** [review]

**Comment by NathanFlurry** [comment]
@MasterPtato renamed pr

**Pull request merged**
