### PR TITLE
fix: update architecture diagram

### PR DESCRIPTION
**Pull request by MasterPtato**
Fixes RVT-4055

### CODE REVIEW

**Comment by MasterPtato** [comment]
* **#1521** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/1521?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/1521?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by NathanFlurry — CHANGES_REQUESTED** [review]
left some notes on figma

**Review by NathanFlurry — CHANGES_REQUESTED** [review]
left some notes on figma. also needs to be included in docs under actor internal. (might just rename to internals)

**Comment by MasterPtato** [comment]
revised figma

**Review by NathanFlurry — CHANGES_REQUESTED** [review]
left a few couple comments.

let's add an architecture diagram page under `advanced > internal` in the docs too. you can link directly to the architecture image file from the readme so we don't have to dupe it.

nit: let's use png export since it's lossless.

**Comment by MasterPtato** [comment]
> left a few couple comments.
> 
> let's add an architecture diagram page under `advanced > internal` in the docs too. you can link directly to the architecture image file from the readme so we don't have to dupe it.
> 
> nit: let's use png export since it's lossless.

Do we need it to be lossess? Its also a massive image file

**Comment by MasterPtato** [comment]
@NathanFlurry revised again

**Comment by NathanFlurry** [comment]
> > left a few couple comments.
> > 
> > let's add an architecture diagram page under `advanced > internal` in the docs too. you can link directly to the architecture image file from the readme so we don't have to dupe it.
> > 
> > nit: let's use png export since it's lossless.
> 
> Do we need it to be lossess? Its also a massive image file

My export was 404 kb. PNG is really good at compression.

**Review by NathanFlurry — APPROVED** [review]

**Pull request closed without merging**
