### PR TITLE
Add nomad health check for restarting

### PR DESCRIPTION
**Pull request by MasterPtato**
Fixes RVT-3646

### CODE REVIEW

**Comment by MasterPtato** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #466** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/466?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/rivet-gg/rivet/466?utm_source=stack-comment).

**Review by AngelOnFira — APPROVED** [review]

**Review by NathanFlurry — COMMENTED** [review]
i'm going to hold off on this for a second since i'm still looking in to the details relating to sporadic tunnel disconnections. it affects gg too.

**Comment by NathanFlurry** [comment]
converting to draft bc of last comment

**Comment by NathanFlurry** [comment]
Closing for now since this issue hasn't come up again, and this has a high probability of unintended side effects/failure states. Will revisit as needed.

**Pull request closed without merging**
