### PR TITLE
Promoting remaining str to String

### PR DESCRIPTION
**Pull request by AngelOnFira**

### CODE REVIEW

**Comment by AngelOnFira** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/279?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #275** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/275?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #276** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/276?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #279** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/279?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/rivet-gg/rivet/279?utm_source=stack-comment).

**Review by NathanFlurry — APPROVED** [review]

**Review by MasterPtato — APPROVED** [review]

**Comment by AngelOnFira** [comment]
### Merge activity

* **Dec 20, 11:54 AM**: [Graphite](https://app.graphite.dev/github/pr/rivet-gg/rivet/279) failed to merge this pull request due to **You're not authorized to push to this branch**. Try your merge again, or report a bug if you see this consistently.

**Comment by AngelOnFira** [comment]
@NathanFlurry can you merge, or could I get branch perms?

**Comment by AngelOnFira** [comment]
### Merge activity

* **Dec 20, 5:12 PM**: @@AngelOnFira started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/rivet-gg/rivet/279).

**Comment by AngelOnFira** [comment]
### Merge activity

* **Dec 20, 5:12 PM**: [Graphite](https://app.graphite.dev/github/pr/rivet-gg/rivet/279) failed to merge this pull request due to **You're not authorized to push to this branch**. Try your merge again, or report a bug if you see this consistently.

**Comment by AngelOnFira** [comment]
### Merge activity

* **Dec 20, 5:21 PM**: @@AngelOnFira started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/rivet-gg/rivet/279).

**Comment by AngelOnFira** [comment]
### Merge activity

* **Dec 20, 5:23 PM**: @@AngelOnFira merged this pull request with [Graphite](https://app.graphite.dev/github/pr/rivet-gg/rivet/279).

**Pull request merged**
