### PR TITLE
Fix GitHub Actions hooks for PRs from public repo

### PR DESCRIPTION
**Pull request by NathanFlurry**

### CODE REVIEW

**Comment by NathanFlurry** [comment]
Current dependencies on/for this PR:
* main
  * **PR #223** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/223?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/rivet-gg/rivet/223?utm_source=stack-comment).

**Comment by NathanFlurry** [comment]
@AngelOnFira can you merge this in to #219 and check if the pull requests show up before approving this?

**Review by AngelOnFira — APPROVED** [review]
@NathanFlurry I was thinking to hold off on this until we got CI secrets sorted for forks, but it does seem to run properly on my fork for what this PR does.

I'll probably hold off on #219 until the CI improvements, just so we can make sure the entire suite runs properly 👍

**Comment by NathanFlurry** [comment]
> @NathanFlurry I was thinking to hold off on this until we got CI secrets sorted for forks, but it does seem to run properly on my fork for what this PR does.
> 
> I'll probably hold off on #219 until the CI improvements, just so we can make sure the entire suite runs properly 👍 

Converting to draft until then

**Comment by NathanFlurry** [comment]
@AngelOnFira Did I see this got fixed in another PR by you earlier today?

**Comment by NathanFlurry** [comment]
@AngelOnFira should we close this?

**Comment by AngelOnFira** [comment]
Ya, I think we can close. The current solution seems like getting people to run a local script to run tests themselves, and then us checking it ourselves before merging. There's good room for future work on it though.

**Pull request closed without merging**
