### PR TITLE
feat: add internal api monolith

### PR DESCRIPTION
**Pull request by MasterPtato**

### CODE REVIEW

**Comment by MasterPtato** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/641?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#641** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/641?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#635** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/635?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#633** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/633?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#632** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/632?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#628** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/628?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#629](https://github.com/rivet-gg/rivet/pull/629) <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/629?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#613** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/613?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#300** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/300?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 2 other dependent PRs ([#380](https://github.com/rivet-gg/rivet/pull/380) <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/380?utm_source=stack-comment-icon" target="_blank">Graphite</a>, [#381](https://github.com/rivet-gg/rivet/pull/381) <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/381?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#373** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/373?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#377** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/377?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#597** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/597?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @MasterPtato and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by NathanFlurry — CHANGES_REQUESTED** [review]
this has to be backwards compatible to support gg nodes with the old request config still on it.

this includes both:
- the hostsni route
- the path

tbh we could rename it to `api-traefik` to keep the path consistent for now.

**Comment by MasterPtato** [comment]
@NathanFlurry there are no old gg nodes, you can't migrate from the old pools to new server provisioning

**Comment by NathanFlurry** [comment]
> @NathanFlurry Could you elaborate? There are no old gg nodes, you can't migrate from the old pools to new server provisioning

Ah right, my bad.

Since we're reworking this in this PR, can we rename api-route to api-traefik-provider? so the full route is just`/traefik-provider/config` (instead of `/route/traefik/config`). i think it's clearer what it actually does.

**Review by NathanFlurry — CHANGES_REQUESTED** [review]
Since we're reworking this in this PR, can we rename api-route to api-traefik-provider? so the full route is just/traefik-provider/config (instead of /route/traefik/config). i think it's clearer what it actually does.

**Comment by MasterPtato** [comment]
@NathanFlurry api-route changes made in new PR https://app.graphite.dev/github/pr/rivet-gg/rivet/697

**Review by NathanFlurry — APPROVED** [review]

**Pull request merged**
