### PR TITLE
Reimplement `bolt create`

### PR DESCRIPTION
**Pull request by MasterPtato**
## Changes
Add `bolt create` command for creating services via templates

### CODE REVIEW

**Comment by NathanFlurry** [comment]
Make sure to merge `main` to make the cargy-deny test pass (#54)

**Comment by NathanFlurry** [comment]
@MasterPtato Is this PR waiting to be merged?

**Comment by MasterPtato** [comment]
> @MasterPtato Is this PR waiting to be merged?

yes

**Comment by MasterPtato** [comment]
@NathanFlurry pstt

**Pull request merged**
