### PR TITLE
Reformat worker mod files

### PR DESCRIPTION
**Pull request by NathanFlurry**
Fixes RVT-3504

Script:

```python
import os
import re

def modify_rust_files(directory):
    for root, _, files in os.walk(directory):
        for file in files:
            if file.endswith('.rs'):
                file_path = os.path.join(root, file)
                with open(file_path, 'r') as f:
                    content = f.read()

                matches = re.findall(r'chirp_worker::workers!\[(.*?)\];', content, re.DOTALL)
                if matches:
                    mods = '\n'.join([f'mod {name.strip()};' for name in matches[0].split(',') if name.strip()])
                    content = mods + '\n\n' + content
                    with open(file_path, 'w') as f:
                        f.write(content)

modify_rust_files('.')
```

### CODE REVIEW

**Comment by NathanFlurry** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #273** <a href="https://app.graphite.dev/github/pr/rivet-gg/rivet/273?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/rivet-gg/rivet/273?utm_source=stack-comment).

**Comment by NathanFlurry** [comment]
@MasterPtato can you validate this does what you expect now?

**Comment by NathanFlurry** [comment]
Oh, just realized the workers macro doesn't do the right thing. One second.

**Comment by MasterPtato** [comment]
@NathanFlurry formatting works now. Should we open a bug report in rust?

**Review by MasterPtato — APPROVED** [review]

**Comment by NathanFlurry** [comment]
> @NathanFlurry formatting works now. Should we open a bug report in rust?

Up to you if you want to spend the time.

**Pull request merged**
