### PR TITLE
Clean up lobby config

### PR DESCRIPTION
**Pull request by MasterPtato**
**Based on max/k8s branch**

Site PR:
https://github.com/rivet-gg/site/pull/7

Fixes SVC-2958

## Changes
- Cleaned up game mode API actions config
- Applied default publicity to /create based on lobby config
- Added client and IP info to external request verification

### CODE REVIEW

**Comment by NathanFlurry** [comment]
@MasterPtato merge conflicts

**Comment by MasterPtato** [comment]
> @MasterPtato merge conflicts

@NathanFlurry fixed

**Comment by NathanFlurry** [comment]
@MasterPtato bolt check still failling

**Comment by MasterPtato** [comment]
@NathanFlurry oops, fixed

**Pull request merged**
